### ISSUE TITLE
Nothing happens after I configured the extension and clicked on Load Issues

### ISSUE THREAD

**Issue by relgames** [cptanalatriste/inflation-tracker-extension#1]
I specified JIRA host and project, saved. Then I click on Load Issues and nothing happens. 
In the console, I see this:
```
Unchecked runtime.lastError: Invalid value for origin pattern https://jira.mycompany.com: Empty path
```

**Comment by relgames** [comment]
I think it can't recognise a root URL (so, no /jira but just hostname). 
I tried to add `/` in the end `https://jira.mycompany.com/` and now it fails with a different error:
```
Error while connecting to: https://jira.mycompany.com//rest/api/2/search?jql=project=AP+and+status=Open+and+assignee+is+null+order+by+priority+desc,created+desc&maxResults=20
```

If I manually open that URL in a browser, it fails indeed, due to double slash `//`
If I remove the second `/`, API works.

**Comment by cptanalatriste** [comment]
Thanks for trying the Fed!

I identified the bug: TheFed wasn't supporting JIRA hosts with empty paths. This new release contains the fix: https://github.com/cptanalatriste/inflation-tracker-extension/releases/download/v0.2-alpha/thefed-for-jira.zip

With this patch, TheFed should generate a correct URL when using a host like `https://jira.mycompany.com/ `.  Please, let me know if the problem persists.
